{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "donkeyfleet.fullname" . }}
  labels:
    {{- include "donkeyfleet.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "donkeyfleet.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
{{- end -}}
